name: Delete dev documentation (artifact)

on:
  workflow_run:
    workflows: ["Delete dev documentation trigger"]
    types:
      - completed


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@fix-token-issue
    secrets:
      comment_bot_token: ${{ secrets.COMMENT_TOKEN }}